### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by damcclean** [ThunderbirdSSG/Thunderbird#17]
I'm planning on setting up configuration on Thunderbird like this:

All configuration is done in a `config.php` file. Users can add their own settings to the file and then they can be used throughout the blade templates etc.

However, I think that we should still keep a `.env` file for things like API keys which shouldn't be in version control.

Let me know what you think!

**Comment by m1guelpf** [comment]
How is it done rn?

**Comment by damcclean** [comment]
Right now it's done just through the `.env` method. I don't really like it because when you deploy to Netlify (or similar), Thunderbird does not build because there is no `.env` file.

Ideally a config file would be better suited to things that don't change between enviroments, like site name, tagline etc.

I tried dabbling around with the `config.php` method this morning but could not manage to get it to read specific keys from the file.

**Comment by damcclean** [comment]
@m1guelpf What do you think?

**Comment by m1guelpf** [comment]
Wouldn't native env vars work with Netlify?

**Comment by damcclean** [comment]
Nah, currently the package we use to get values from the `env` doesnot seem to like the way that Netlify do their configuration stuff. I've tried and failed to get it working.

**Comment by m1guelpf** [comment]
Have you tried using Synfony's dotenv? I recently PRd this to Jigaw, you can take a look at my code ;D

**Comment by damcclean** [comment]
That's what I was using

**Comment by damcclean** [comment]
c0166cc
